development:
  FACEBOOK_CONSUMER_KEY: '733661216688700'
  FACEBOOK_CONSUMER_SECRET: 'd896d32569ce682bbfd99fb69846c90a'
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
staging:
  FACEBOOK_CONSUMER_KEY: '733661216688700'
  FACEBOOK_CONSUMER_SECRET: 'd896d32569ce682bbfd99fb69846c90a'
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
production:
  FACEBOOK_CONSUMER_KEY: '733661216688700'
  FACEBOOK_CONSUMER_SECRET: 'd896d32569ce682bbfd99fb69846c90a'
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
