development:
  FACEBOOK_CONSUMER_KEY: '733661216688700'
  FACEBOOK_CONSUMER_SECRET: 'd896d32569ce682bbfd99fb69846c90a'
  MONGO_HOST: 'localhost'
  MONGO_PORT: '27017'
  MONGO_DB_NAME: 'ankusa'
  MONGO_USERNAME: ''
  MONGO_PASSWORD: ''
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
staging:
  FACEBOOK_CONSUMER_KEY: '733661216688700'
  FACEBOOK_CONSUMER_SECRET: 'd896d32569ce682bbfd99fb69846c90a'
  MONGO_HOST: ''
  MONGO_PORT: ''
  MONGO_DB_NAME: ''
  MONGO_USERNAME: ''
  MONGO_PASSWORD: ''
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
production:
  FACEBOOK_CONSUMER_KEY: '733661216688700'
  FACEBOOK_CONSUMER_SECRET: 'd896d32569ce682bbfd99fb69846c90a'
  MONGO_USERNAME: 'patonty'
  MONGO_PASSWORD: 'betonty'
  #TWITTER_KEY: ''
  #TWITTER_SECRET: ''
  #TWITTER_OAUTH_TOKEN: ''
  #TWITTER_OAUTH_TOKEN_SECRET: ''
