# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71fde7ab39f145b4f00ee4ec26b2f0734957b72655316be264c94dc0f49ff34b4f6592f5a897b5bbfb980fbdd380528e9e9593478384378305ec20043edc3797

test:
  secret_key_base: b4e014458152851889ac28d35584bdfc21d03bf91a31624af91a559cbed8f26c5f6ec58fa81535683b2d6c02a4f990a8618a7d3cd90d9e3096feb3f2e4741801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
